### ISSUE TITLE
version of emoji

### ISSUE THREAD

**Issue by Tolmino** [official-antique/InstaPy#1]

**Comment by Tolmino** [comment]
i have that request :

 File "/usr/lib/python3.6/site-packages/instapy-0.6.9-py3.6.egg/instapy/util.py", line 27, in <module>
    from emoji import EMOJI_DATA
ImportError: cannot import name 'EMOJI_DATA'

and i have resolved in that way :
pip3 uninstall emoji
pip3 install emoji==1.7

**Comment by Tolmino** [comment]
i don't know what version i had ...

**Comment by official-antique** [comment]
@Tolmino apologies, did not see this before. EMOJI_DATA appears to have been added in v2.0.0 or v2.1.0 of `emoji`. I've fixed it in my fork as far as I'm aware but if not I'm happy to do so.

**Comment by official-antique** [comment]
Fixed in [commit](https://github.com/official-antique/InstaPy/commit/791759c27db7ff26ec60f7bfe44aeeb1d27df400).
